<#--package ${cfg.beanDbBeanPackage};-->

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

<#if table.importBeanList??>
    <#list table.importBeanList as item>
import ${item};
    </#list>
</#if>

/**
WARNING:
this code is generated by code-auto
please DO NOT modify this file
**/
@Data
@ApiModel("${table.tableComment}")
public class ${table.beanName}Dto{
<#list table.propertyList as col>
<#if col.propertyName !='delFlag'>
    @ApiModelProperty("${col.columnComment}")
    private ${col.propertyType} ${col.propertyName};
</#if>
</#list>
    @ApiModelProperty(value = "请求id", hidden = true)
    private String uuid;

<#--<#list table.propertyList as col>-->
<#--    public ${col.propertyType} get${col.propertyName?cap_first}() {-->
<#--    return ${col.propertyName};-->
<#--    }-->

<#--    public void set${col.propertyName?cap_first}(${col.propertyType} ${col.propertyName}) {-->
<#--    this.${col.propertyName} = ${col.propertyName};-->
<#--    }-->

<#--</#list>-->
}
