package ${cfg.beanDbBeanPackage};


import lombok.Data;

<#if table.importBeanList??>
    <#list table.importBeanList as item>
import ${item};
    </#list>
</#if>

/**
WARNING:
this code is generated by code-auto
please DO NOT modify this file
**/
@Data
public class ${table.beanName}{
<#list table.propertyList as col>
    <#if col.columnComment?has_content>
    /**
     * ${col.columnComment}
     */
    </#if>
    private ${col.propertyType} ${col.propertyName};
</#list>

<#--<#list table.propertyList as col>-->
<#--    public ${col.propertyType} get${col.propertyName?cap_first}() {-->
<#--    return ${col.propertyName};-->
<#--    }-->

<#--    public void set${col.propertyName?cap_first}(${col.propertyType} ${col.propertyName}) {-->
<#--    this.${col.propertyName} = ${col.propertyName};-->
<#--    }-->

<#--</#list>-->
}
