<#--package ${cfg.beanDbBeanPackage};-->

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

<#if table.importBeanList??>
    <#list table.importBeanList as item>
        import ${item};
    </#list>
</#if>

/**
WARNING:
this code is generated by code-auto
please DO NOT modify this file
**/
@Data
@ApiModel("${table.tableComment}")
public class ${table.beanName}Vo{

<#list table.propertyList as col>
<#if !(col.propertyName =='modifyDate'|| col.propertyName =='createDate' || col.propertyName =='delFlag')>
    @ApiModelProperty("${col.columnComment}")
    private ${col.propertyType} ${col.propertyName};
</#if>
</#list>

}
