<#--package ${cfg.beanDbBeanPackage};-->

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

<#if table.importBeanList??>
    <#list table.importBeanList as item>
import ${item};
    </#list>
</#if>

/**
WARNING:
this code is generated by code-auto
please DO NOT modify this file
**/
@Data
@ApiModel("${table.tableComment}")
public class ${table.beanName}Dto{

    @ApiModelProperty(value = "当前页", example = "1", required = true)
    private Integer pageNum;
    @ApiModelProperty(value = "每页的数量", example = "15", required = true)
    private Integer pageSize;
    @ApiModelProperty("排序字段")
    private String sortColumn;
    @ApiModelProperty("排序方式")
    private String sortType;

}
