spring:
  datasource:
    url: jdbc:mysql://11.12.12.203:3306/zccuserdevdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: zccuserdevdb
    password: 123456
#    username: root
#    password: DpgZ7jMoro*<
    driver-class-name: com.mysql.cj.jdbc.Driver


schema: zccuserdevdb
output.dir: E:/zt-auto
template.dir:
table.include: mechanism_column_config
table.ignored:
# boss-base 内基础bean的包
#common.bean.package: cn.victorplus.boss.pay.paycore.mapper.base
#common.mapper.package: cn.victorplus.boss.pay.paycore.mapper
# 生成的项目的包名
bean.db.bean.package: com.ect.icb.manage.domain.pojo
bean.mapper.package: com.ect.icb.manage.data.mapper
